# Generated by Django 5.2.12 on 2026-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='diary.hashtag'),
        ),
    ]
