# Generated by Django 5.2.12 on 2026-05-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
